export const ITEM_TYPES = {
  SNAKE: 1,
  FOOD: 2
}

export const FOOD_TYPES = {
  FRUIT: 1,
  POISON: 2
}

export const SNAKE_DIRECTIONS = {
  WEST: 1,
  NORTH: 2,
  EAST: 3,
  SOUTH: 4
}

export const SNAKE_OPPOSITE_DIRECTIONS = {
  [SNAKE_DIRECTIONS.WEST]: SNAKE_DIRECTIONS.EAST,
  [SNAKE_DIRECTIONS.NORTH]: SNAKE_DIRECTIONS.SOUTH,
  [SNAKE_DIRECTIONS.EAST]: SNAKE_DIRECTIONS.WEST,
  [SNAKE_DIRECTIONS.SOUTH]: SNAKE_DIRECTIONS.NORTH
}

export const SNAKE_ALLOWED_DIRECTIONS = {
  [SNAKE_DIRECTIONS.NORTH]: [SNAKE_DIRECTIONS.EAST, SNAKE_DIRECTIONS.WEST],
  [SNAKE_DIRECTIONS.EAST]: [SNAKE_DIRECTIONS.NORTH, SNAKE_DIRECTIONS.SOUTH],
  [SNAKE_DIRECTIONS.SOUTH]: [SNAKE_DIRECTIONS.EAST, SNAKE_DIRECTIONS.WEST],
  [SNAKE_DIRECTIONS.WEST]: [SNAKE_DIRECTIONS.NORTH, SNAKE_DIRECTIONS.SOUTH]
}

export const KEYBOARD_DIRECTION_MAPPER = {
  37: SNAKE_DIRECTIONS.WEST,
  38: SNAKE_DIRECTIONS.NORTH,
  39: SNAKE_DIRECTIONS.EAST,
  40: SNAKE_DIRECTIONS.SOUTH
}

export const KEYBOARD_REVERTED_DIRECTION_MAPPER = {
  37: SNAKE_DIRECTIONS.EAST,
  38: SNAKE_DIRECTIONS.SOUTH,
  39: SNAKE_DIRECTIONS.WEST,
  40: SNAKE_DIRECTIONS.NORTH
}

export const SNAKE_HEALTHS = {
  HEALTHY: 1,
  CONFUSED: 2
}

export const SNAKE_DIGESTION_CAUSES = {
  [FOOD_TYPES.FRUIT]: SNAKE_HEALTHS.HEALTHY,
  [FOOD_TYPES.POISON]: SNAKE_HEALTHS.CONFUSED
}

export const MENU = {
  DEFAULT: 1,
  SCOREBOARD: 2,
  HOWTOPLAY: 3,
  LOSTGAME: 4,
  SAVERANK: 5,
  SAVEDRANK: 6
}

export const DISPLAYS = {
  LANDSCAPE_COLS: 64,
  LANDSCAPE_ROWS: 24,
  PORTRAIT_COLS: 32,
  PORTRAIT_ROWS: 48
}
